trigger:
  tags:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Publish
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      curl -sSL https://install.python-poetry.org | python3 -
    displayName: 'Install Poetry'

  - script: |
      poetry install
    displayName: 'Install dependencies'

  - script: |
      poetry build
    displayName: 'Build'

  - task: EsrpRelease@2
    inputs:
      ConnectedServiceName: 'OM-ESRP-Release-Publishing'
      Intent: 'PackageDistribution'
      ContentType: 'PyPi'
      PackageLocation: 'dist'
      Owners: 'jiuboguo@microsoft.com'
      Approvers: 'jiuboguo@microsoft.com'
      ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
      MainPublisher: 'ESRPRELPACMAN'
      DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'
