trigger:
  tags:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Publish
  
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      curl -sSL https://install.python-poetry.org | python3 -
    displayName: 'Install Poetry'

  - script: |
      poetry install
    displayName: 'Install dependencies'
```
